version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service/users.db:/auth-service/users.db
  storage-service:
    build: ./storage-service
    ports:
      - "8001:8000"
    volumes:
      - ./storage-service/files.db:/storage-service/files.db
  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:80"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
